on:
  push:
    branches:
      - master
name: Release package
jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      release_left: ${{ steps.release.outputs.package-left--release_created }}
      release_right: ${{ steps.release.outputs.package-right--release_created }}
      paths_released: ${{ steps.release.outputs.paths-released }}
      git_tag_left: ${{ steps.release.outputs.package-left--tag_name }}
      git_tag_right: ${{ steps.release.outputs.package-right--tag_name }}
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          command: manifest
          default-branch: master
      - run: echo "Releases created -- ${{ steps.release.outputs.releases_created }}"
      - run: echo "Release left created -- ${{ steps.release.outputs.package-left--release_created }}"
      - run: echo "Release right created -- ${{ steps.release.outputs.package-right--release_created }}"
      - run: echo "Paths released -- ${{ steps.release.outputs.paths_released }}"
      - run: echo "Tag left -- ${{ steps.release.outputs.git_tag_left }}"
      - run: echo "Tag right -- ${{ steps.release.outputs.git_tag_right }}"

  echo-package-left:
    runs-on: ubuntu-latest
    needs: [create-release]
    name: Release ${{ needs.create-release.outputs.git_tag_left }}
    if: ${{ needs.create-release.outputs.release_left }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ needs.create-release-outputs.git_tag_left }}
      - run: echo "Package left released -- ${{ needs.create-release.outputs.git_tag_left }}"
      - run: cat package-left/package.json | grep "version"

  echo-package-right:
    runs-on: ubuntu-latest
    needs: [create-release]
    name: Release ${{ needs.create-release.outputs.git_tag_right }}
    if: ${{ needs.create-release.outputs.release_right }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ needs.create-release-outputs.git_tag_right }}
      - run: echo "Package right released -- ${{ needs.create-release.outputs.git_tag_right }}"
      - run: cat package-right/package.json | grep "version"
