on:
  push:
    branches:
      - master
name: release-please-package
jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.package-left--release_created }}
      paths_released: ${{ steps.release.outputs.paths-released }}
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          command: manifest
          default-branch: master
      - run: echo "Releases created -- ${{ steps.release.outputs.releases_created }}"
      - run: echo "Release left created -- ${{ steps.release.outputs.package-left--release_created }}"
      - run: echo "Release right created -- ${{ steps.release.outputs.package-right--release_created }}"
      - run: echo "Paths released -- ${{ steps.release.outputs.paths_released }}"

  echo:
    runs-on: ubuntu-latest
    needs: [create-release]
    if: ${{ needs.create-release.outputs.release_created }}
    steps:
      - run: echo "Release created"
