on:
  push:
    branches:
      - master
name: release-please-package-right
jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          package-name: release-package-right
          path: package-right
          monorepo-tags: true
          signoff: "Robert Kolner <robert.kolner@noaignite.com>"
      - run: echo "${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }} -- ${{ steps.release.outputs.release_created }}"

  echo:
    runs-on: ubuntu-latest
    needs: [create-release]
    if: ${{ needs.create-release.outputs.release_created }}
    steps:
      - run: echo "Release created"
