on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

name: validate-pr-title
jobs:
  validate-pr-title:
    runs-on: ubuntu-latest
    steps:
      - uses: deepakputhraya/action-pr-title@master
        with:
          allowed_prefixes: "chore,docs,feat,fix,refactor,style,test"
          prefix_case_sensitive: true
          min_length: 5
